import React from 'react';
import { Download } from 'lucide-react';

const mockReports = [
  {
    id: 1,
    name: 'Q1 2024 Driver Performance Summary',
    dateGenerated: '2024-04-05',
    generatedBy: 'Admin',
  },
  {
    id: 2,
    name: 'March 2024 Earnings Report',
    dateGenerated: '2024-04-01',
    generatedBy: 'System',
  },
  {
    id: 3,
    name: 'Q1 2024 Rider Feedback Analysis',
    dateGenerated: '2024-04-02',
    generatedBy: 'Admin',
  },
  {
    id: 4,
    name: 'February 2024 Ride Statistics',
    dateGenerated: '2024-03-01',
    generatedBy: 'System',
  },
  {
    id: 5,
    name: 'January 2024 Complaint Report',
    dateGenerated: '2024-02-01',
    generatedBy: 'Admin',
  },
];

export const Reports = () => {
  return (
    <div className="p-6 bg-gray-50 min-h-screen">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-3xl font-bold text-gray-800">Reports</h1>
        <div className="flex items-center space-x-4">
          <select className="p-2 border rounded-md">
            <option>All Reports</option>
            <option>Driver Performance</option>
            <option>Earnings</option>
            <option>Ride Statistics</option>
            <option>User Feedback</option>
          </select>
          <input type="date" className="p-2 border rounded-md" />
          <button className="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700">
            Generate Report
          </button>
        </div>
      </div>

      <div className="bg-white p-4 rounded-lg shadow">
        <table className="min-w-full divide-y divide-gray-200">
          <thead className="bg-gray-50">
            <tr>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Report Name
              </th>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Date Generated
              </th>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Generated By
              </th>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Actions
              </th>
            </tr>
          </thead>
          <tbody className="bg-white divide-y divide-gray-200">
            {mockReports.map((report) => (
              <tr key={report.id}>
                <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                  {report.name}
                </td>
                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                  {report.dateGenerated}
                </td>
                <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                  {report.generatedBy}
                </td>
                <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                  <button className="text-blue-600 hover:text-blue-900 flex items-center">
                    <Download size={16} className="mr-1" />
                    Download
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}; 